import translations from "../public/locales/en/translation.json";
import fs from "fs";
import { join } from "path";
import prettier from "prettier";

const keys: string[] = [];

type TranslationRecord = {
	[P in string]: string | TranslationRecord;
};

const traverseTranslations = (obj: TranslationRecord, path: string[]) => {
	Object.keys(obj).forEach((key) => {
		if (key.startsWith("_")) {
			return;
		}
		const objOrString = obj[key];
		if (typeof objOrString === "string") {
			keys.push([...path, key].join("."));
		} else {
			traverseTranslations(objOrString, [...path, key]);
		}
	});
};

traverseTranslations(translations, []);

const s = `
// this is autogenerated by running \`npm run gen:i18:keys\`
export type TranslationKeys =
${keys.map((k) => `  "${k}"`).join("|\n")}
`;

fs.writeFileSync(
	join(__dirname, "../src/generated/translationKeys.ts"),
	prettier.format(s, { parser: "babel" })
);
