import { EmojiData } from "emoji-mart";

export const customEmojis = [
  {
    name: "monkaS",
    short_names: ["monkaS"],
    keywords: ["monkas", "pepe"],
    imageUrl: "/emotes/monkas.png",
  },
  {
    name: "HYPERS",
    short_names: ["HYPERS"],
    keywords: ["hypers", "pepe"],
    imageUrl: "/emotes/hypers.png",
  },
  {
    name: "pepeD",
    short_names: ["pepeD"],
    keywords: ["peped", "pepe"],
    imageUrl: "/emotes/peped.gif",
  },
  {
    name: "Pepega",
    short_names: ["Pepega"],
    keywords: ["pepega", "pepe"],
    imageUrl: "/emotes/pepega.png",
  },
  {
    name: "Sadge",
    short_names: ["Sadge"],
    keywords: ["sadge", "pepe"],
    imageUrl: "/emotes/sadge.png",
  },
  {
    name: "catJAM",
    short_names: ["catJAM"],
    keywords: ["catjam", "vibe"],
    imageUrl: "/emotes/catjam.gif",
  },
  {
    name: "Thonk",
    short_names: ["Thonk"],
    keywords: ["thonk", "think"],
    imageUrl: "/emotes/thonk.png",
  },
  {
    name: "DogeHouse",
    short_names: ["DogeHouse"],
    keywords: ["dogehouse", "doge"],
    imageUrl: "/emotes/dogehouse.png",
  },
  {
    name: "SadHouse",
    short_names: ["SadHouse"],
    keywords: ["dogehouse", "doge", "sadhouse"],
    imageUrl: "/emotes/sadhouse.png",
  },
  {
    name: "CoolHouse",
    short_names: ["CoolHouse"],
    keywords: ["dogehouse", "doge", "coolhouse"],
    imageUrl: "/emotes/coolhouse.png",
  },
  {
    name: "WinkHouse",
    short_names: ["WinkHouse"],
    keywords: ["dogehouse", "doge", "winkhouse"],
    imageUrl: "/emotes/winkhouse.png",
  },
  {
    name: "SupriseHouse",
    short_names: ["SupriseHouse"],
    keywords: ["dogehouse", "doge", "suprisehouse", "shock"],
    imageUrl: "/emotes/suprisehouse.png",
  },
  {
    name: "NeutralHouse",
    short_names: ["NeutralHouse"],
    keywords: ["dogehouse", "doge", "neutralhouse"],
    imageUrl: "/emotes/neutralhouse.png",
  },
  {
    name: "WAYTOODANK",
    short_names: ["WAYTOODANK"],
    keywords: ["dank", "feelsdankman"],
    imageUrl: "/emotes/waytoodank.gif",
  },
  {
    name: "CryptoBTC",
    short_names: ["CryptoBTC"],
    keywords: ["crypto", "btc", "bitcoin"],
    imageUrl: "/emotes/cryptoBTC.png",
  },
  {
    name: "CryptoETH",
    short_names: ["CryptoETH"],
    keywords: ["crypto", "eth", "ethereum"],
    imageUrl: "/emotes/cryptoETH.png",
  },
  {
    name: "CryptoBNB",
    short_names: ["CryptoBNB"],
    keywords: ["crypto", "bnb", "binance"],
    imageUrl: "/emotes/cryptoBNB.png",
  },
  {
    name: "CryptoLTC",
    short_names: ["CryptoLTC"],
    keywords: ["crypto", "ltc", "litecoin"],
    imageUrl: "/emotes/cryptoLTC.png",
  },
  {
    name: "CryptoBCH",
    short_names: ["CryptoBCH"],
    keywords: ["crypto", "bch", "bitcoin", "bitcoincash"],
    imageUrl: "/emotes/cryptoBCH.png",
  },
  {
    name: "CryptoDOGE",
    short_names: ["CryptoDOGE"],
    keywords: ["crypto", "doge", "dogecoin", "bestcoin"],
    imageUrl: "/emotes/cryptoDOGE.png",
  },
  {
    name: "CryptoSUSHI",
    short_names: ["CryptoSUSHI"],
    keywords: ["crypto", "sushi", "swap", "sushiswap"],
    imageUrl: "/emotes/cryptoSUSHI.png",
  },
  {
    name: "CryptoTRON",
    short_names: ["CryptoTRON"],
    keywords: ["crypto", "tron"],
    imageUrl: "/emotes/cryptoTron.png",
  },
  {
    name: "CryptoZEC",
    short_names: ["CryptoZEC"],
    keywords: ["crypto", "zec", "zcash"],
    imageUrl: "/emotes/cryptoZEC.png",
  },
  {
    name: "CryptoETC",
    short_names: ["CryptoETC"],
    keywords: ["crypto", "etc", "ethereum", "ethereumclassic"],
    imageUrl: "/emotes/cryptoETC.png",
  },
  {
    name: "CryptoCAKE",
    short_names: ["CryptoCAKE"],
    keywords: ["crypto", "cake", "swap", "pancakeswap"],
    imageUrl: "/emotes/cryptoCAKE.png",
  },
  {
    name: "CryptoADA",
    short_names: ["CryptoADA"],
    keywords: ["crypto", "ada", "cardano"],
    imageUrl: "/emotes/cryptoADA.png",
  },
  {
    name: "CryptoXRP",
    short_names: ["CryptoXRP"],
    keywords: ["crypto", "xrp", "ripple"],
    imageUrl: "/emotes/cryptoXRP.png",
  },
  {
    name: "CryptoUSDC",
    short_names: ["CryptoUSDC"],
    keywords: ["crypto", "usdc", "usdcoin"],
    imageUrl: "/emotes/cryptoUSDC.png",
  },
  {
    name: "DodgyCoin",
    short_names: ["DodgyCoin"],
    keywords: ["crypto", "doge", "dodgycoin"],
    imageUrl: "/emotes/dodgyCoin.png",
  },
  {
    name: "catJAM",
    short_names: ["catJAM"],
    keywords: ["catjam", "vibe"],
    imageUrl: "/emotes/catjam.gif",
  },
  {
    name: "Thonk",
    short_names: ["Thonk"],
    keywords: ["thonk", "think"],
    imageUrl: "/emotes/thonk.png",
  },
  {
    name: "DogeHouse",
    short_names: ["DogeHouse"],
    keywords: ["dogehouse", "doge"],
    imageUrl: "/emotes/dogehouse.png",
  },
  {
    name: "SadHouse",
    short_names: ["SadHouse"],
    keywords: ["dogehouse", "doge", "sadhouse"],
    imageUrl: "/emotes/sadhouse.png",
  },
  {
    name: "CoolHouse",
    short_names: ["CoolHouse"],
    keywords: ["dogehouse", "doge", "coolhouse"],
    imageUrl: "/emotes/coolhouse.png",
  },
  {
    name: "WinkHouse",
    short_names: ["WinkHouse"],
    keywords: ["dogehouse", "doge", "winkhouse"],
    imageUrl: "/emotes/winkhouse.png",
  },
  {
    name: "SupriseHouse",
    short_names: ["SupriseHouse"],
    keywords: ["dogehouse", "doge", "suprisehouse", "shock"],
    imageUrl: "/emotes/suprisehouse.png",
  },
  {
    name: "NeutralHouse",
    short_names: ["NeutralHouse"],
    keywords: ["dogehouse", "doge", "neutralhouse"],
    imageUrl: "/emotes/neutralhouse.png",
  },
  {
    name: "WAYTOODANK",
    short_names: ["WAYTOODANK"],
    keywords: ["dank", "feelsdankman"],
    imageUrl: "/emotes/waytoodank.gif",
  },
  {
    name: "CryptoBTC",
    short_names: ["CryptoBTC"],
    keywords: ["crypto", "btc", "bitcoin"],
    imageUrl: "/emotes/cryptoBTC.png",
  },
  {
    name: "ThugPepe",
    short_names: ["ThugPepe"],
    keywords: ["dogehouse", "doge", "thugpepe"],
    imageUrl: "/emotes/thugpepe.png",
  },
  {
    name: "CryptoETH",
    short_names: ["CryptoETH"],
    keywords: ["crypto", "eth", "ethereum"],
    imageUrl: "/emotes/cryptoETH.png",
  },
  {
    name: "CryptoBNB",
    short_names: ["CryptoBNB"],
    keywords: ["crypto", "bnb", "binance"],
    imageUrl: "/emotes/cryptoBNB.png",
  },
  {
    name: "CryptoLTC",
    short_names: ["CryptoLTC"],
    keywords: ["crypto", "ltc", "litecoin"],
    imageUrl: "/emotes/cryptoLTC.png",
  },
  {
    name: "CryptoBCH",
    short_names: ["CryptoBCH"],
    keywords: ["crypto", "bch", "bitcoin", "bitcoincash"],
    imageUrl: "/emotes/cryptoBCH.png",
  },
  {
    name: "CryptoDOGE",
    short_names: ["CryptoDOGE"],
    keywords: ["crypto", "doge", "dogecoin", "bestcoin"],
    imageUrl: "/emotes/cryptoDOGE.png",
  },
  {
    name: "CryptoSUSHI",
    short_names: ["CryptoSUSHI"],
    keywords: ["crypto", "sushi", "swap", "sushiswap"],
    imageUrl: "/emotes/cryptoSUSHI.png",
  },
  {
    name: "CryptoZEC",
    short_names: ["CryptoZEC"],
    keywords: ["crypto", "zec", "zcash"],
    imageUrl: "/emotes/cryptoZEC.png",
  },
  {
    name: "CryptoETC",
    short_names: ["CryptoETC"],
    keywords: ["crypto", "etc", "ethereum", "ethereumclassic"],
    imageUrl: "/emotes/cryptoETC.png",
  },
  {
    name: "CryptoCAKE",
    short_names: ["CryptoCAKE"],
    keywords: ["crypto", "cake", "swap", "pancakeswap"],
    imageUrl: "/emotes/cryptoCAKE.png",
  },
  {
    name: "CryptoADA",
    short_names: ["CryptoADA"],
    keywords: ["crypto", "ada", "cardano"],
    imageUrl: "/emotes/cryptoADA.png",
  },
  {
    name: "CryptoXRP",
    short_names: ["CryptoXRP"],
    keywords: ["crypto", "xrp", "ripple"],
    imageUrl: "/emotes/cryptoXRP.png",
  },
  {
    name: "CryptoUSDC",
    short_names: ["CryptoUSDC"],
    keywords: ["crypto", "usdc", "usdcoin"],
    imageUrl: "/emotes/cryptoUSDC.png",
  },
  {
    name: "DodgyCoin",
    short_names: ["DodgyCoin"],
    keywords: ["crypto", "doge", "dodgycoin"],
    imageUrl: "/emotes/dodgyCoin.png",
  },
  {
    name: "blaze",
    short_names: ["blaze"],
    keywords: ["blaze", "yes", "snark"],
    imageUrl: "/emotes/blaze.png",
  },
  {
    name: "blobDance",
    short_names: ["blobDance"],
    keywords: ["blobDance", "vibe"],
    imageUrl: "/emotes/blobdance.gif",
  },
  {
    name: "pepeJAM",
    short_names: ["pepeJAM"],
    keywords: ["pepeJAM", "pepe"],
    imageUrl: "/emotes/pepejam.gif",
  },
  {
    name: "PepePls",
    short_names: ["PepePls"],
    keywords: ["PepePls", "pepe"],
    imageUrl: "/emotes/pepepls.gif",
  },
  {
    name: "Clap",
    short_names: ["Clap"],
    keywords: ["Clap"],
    imageUrl: "/emotes/clap.gif",
  },
  {
    name: "EZ",
    short_names: ["EZ"],
    keywords: ["EZ", "pepe"],
    imageUrl: "/emotes/ez.png",
  },
  {
    name: "peepoHey",
    short_names: ["peepoHey"],
    keywords: ["peepoHey", "peepo", "pepe"],
    imageUrl: "/emotes/peepohey.gif",
  },
  {
    name: "FeelsGoodMan",
    short_names: ["FeelsGoodMan"],
    keywords: ["FeelsGoodMan", "pepe"],
    imageUrl: "/emotes/feelsgoodman.png",
  },
  {
    name: "GitHub",
    short_names: ["GitHub"],
    keywords: ["app", "git", "github"],
    imageUrl: "/emotes/github.png",
  },
  {
    name: "Elixir",
    short_names: ["Elixir"],
    keywords: ["app", "elixir"],
    imageUrl: "/emotes/elixir.png",
  },
  {
    name: "NextJS",
    short_names: ["NextJS"],
    keywords: ["app", "next", "js"],
    imageUrl: "/emotes/nextjs.png",
  },
  {
    name: "React",
    short_names: ["React"],
    keywords: ["app", "react", "js"],
    imageUrl: "/emotes/react.png",
  },
  {
    name: "Electron",
    short_names: ["Electron"],
    keywords: ["app", "electron"],
    imageUrl: "/emotes/electron.png",
  },
  {
    name: "BeardGuyR",
    short_names: ["BeardGuyR"],
    keywords: ["meme", "beard", "guy"],
    imageUrl: "/emotes/beardguyright.png",
  },
  {
    name: "BeardGuyL",
    short_names: ["BeardGuyL"],
    keywords: ["meme", "beard", "guy"],
    imageUrl: "/emotes/beardguyleft.png",
  },
  {
    name: "MemeMan",
    short_names: ["MemeMan"],
    keywords: ["meme", "guy"],
    imageUrl: "/emotes/mememan.png",
  },
  {
    name: "NPC",
    short_names: ["NPC"],
    keywords: ["meme", "npc", "guy"],
    imageUrl: "/emotes/npc.png",
  },
  {
    name: "SmudgeCat",
    short_names: ["SMudgeCat"],
    keywords: ["meme", "cat"],
    imageUrl: "/emotes/smudgecat.png",
  },
  {
    name: "Stonks",
    short_names: ["Stonks"],
    keywords: ["meme", "crypto", "guy"],
    imageUrl: "/emotes/stonks.png",
  },
  {
    name: "Stinks",
    short_names: ["Stinks"],
    keywords: ["meme", "crypto", "guy"],
    imageUrl: "/emotes/stinks.png",
  },
  {
    name: "IWMD",
    short_names: ["IWMD"],
    keywords: ["meme", "dude", "wednesday", "frog"],
    imageUrl: "/emotes/wednesday.png",
  },
  {
    name: "PreSponge",
    short_names: ["PreSponge"],
    keywords: ["meme", "spongebob"],
    imageUrl: "/emotes/presponge.png",
  },
  {
    name: "sPonGeBoB",
    short_names: ["sPonGeBoB"],
    keywords: ["meme", "spongebob"],
    imageUrl: "/emotes/sPonGeBoB.png",
  },
  {
    name: "PurpleDogeHouse",
    short_names: ["PurpleDogeHouse"],
    keywords: ["purple", "dogehouse", "doge"],
    imageUrl: "/emotes/purpledogehouse.png",
  },
  {
    name: "OrangeDogeHouse",
    short_names: ["OrangeDogeHouse"],
    keywords: ["orange", "dogehouse", "doge"],
    imageUrl: "/emotes/orangedogehouse.png",
  },
  {
    name: "CyaneDogeHouse",
    short_names: ["CyaneDogeHouse"],
    keywords: ["cyan", "dogehouse", "doge"],
    imageUrl: "/emotes/cyandogehouse.png",
  },
].map((e) => ({ ...e, customCategory: "Custom", text: "", emoticons: [] }));

export const emoteMap: Record<string, string> = {};

export type CustomEmote = EmojiData & {
  customCategory: string;
};

customEmojis.forEach((e) => {
  emoteMap[e.name] = e.imageUrl;
});
