import { ImageSourcePropType } from "react-native";

export const customEmojis = [
  {
    name: "heart",
    short_names: ["heart", "<3"],
    keywords: ["heart", "<3"],
    imageUrl: require("../../../assets/images/emotes/heart.png"),
  },
  {
    name: "brokenHeart",
    short_names: ["brokenHeart"],
    keywords: ["broken", "heart", "broken heart", "brokenHeart"],
    imageUrl: require("../../../assets/images/emotes/brokenHeart.gif"),
  },
  {
    name: "obamium",
    short_names: ["obama"],
    keywords: ["obama", "prism", "obamium"],
    imageUrl: require("../../../assets/images/emotes/obamium.png"),
  },
  {
    name: "IntelxAMD",
    short_names: ["intel"],
    keywords: ["intel", "amd", "intelxamd"],
    imageUrl: require("../../../assets/images/emotes/IntelxAMD.png"),
  },
  {
    name: "linus",
    short_names: ["linus"],
    keywords: ["linus", "tech", "linustechtips"],
    imageUrl: require("../../../assets/images/emotes/linus.png"),
  },
  {
    name: "redDogeHouse",
    short_names: ["redDogeHouse"],
    keywords: ["red", "dogehouse", "doge"],
    imageUrl: require("../../../assets/images/emotes/reddogehouse.png"),
  },
  {
    name: "this",
    short_names: ["this"],
    keywords: ["this"],
    imageUrl: require("../../../assets/images/emotes/this.png"),
  },
  {
    name: "brownDogeHouse",
    short_names: ["brownDogeHouse"],
    keywords: ["brown", "dogehouse", "doge"],
    imageUrl: require("../../../assets/images/emotes/browndogehouse.png"),
  },
  {
    name: "shut",
    short_names: ["shut"],
    keywords: ["shut"],
    imageUrl: require("../../../assets/images/emotes/shut.png"),
  },
  {
    name: "blobWtf",
    short_names: ["blobWtf"],
    keywords: ["blob", "wtf"],
    imageUrl: require("../../../assets/images/emotes/blobwtf.png"),
  },
  {
    name: "WhaleThonk",
    short_names: ["WhaleThonk"],
    keywords: ["whale", "thonk", "thinking", "what"],
    imageUrl: require("../../../assets/images/emotes/whalethonk.png"),
  },
  {
    name: "PogChamp",
    short_names: ["PogChamp"],
    keywords: ["pogchamp", "pog"],
    imageUrl: require("../../../assets/images/emotes/pogchamp.png"),
  },
  {
    name: "monkaS",
    short_names: ["monkaS"],
    keywords: ["monkas", "pepe"],
    imageUrl: require("../../../assets/images/emotes/monkas.png"),
  },
  {
    name: "HYPERS",
    short_names: ["HYPERS"],
    keywords: ["hypers", "pepe"],
    imageUrl: require("../../../assets/images/emotes/hypers.png"),
  },
  {
    name: "peped",
    short_names: ["peped"],
    keywords: ["peped", "pepe"],
    imageUrl: require("../../../assets/images/emotes/peped.gif"),
  },
  {
    name: "Pepega",
    short_names: ["Pepega"],
    keywords: ["pepega", "pepe"],
    imageUrl: require("../../../assets/images/emotes/pepega.png"),
  },
  {
    name: "peepoHappy",
    short_names: ["peepoHappy"],
    keywords: ["peepohappy", "peepo", "pepe"],
    imageUrl: require("../../../assets/images/emotes/peepohappy.png"),
  },
  {
    name: "peepoHug",
    short_names: ["peepoHug"],
    keywords: ["peepohug", "peepo", "pepe"],
    imageUrl: require("../../../assets/images/emotes/peepohug.png"),
  },
  {
    name: "Sadge",
    short_names: ["Sadge"],
    keywords: ["sadge", "pepe"],
    imageUrl: require("../../../assets/images/emotes/sadge.png"),
  },
  {
    name: "catJAM",
    short_names: ["catJAM"],
    keywords: ["catjam", "vibe"],
    imageUrl: require("../../../assets/images/emotes/catjam.gif"),
  },
  {
    name: "Thonk",
    short_names: ["Thonk"],
    keywords: ["thonk", "think"],
    imageUrl: require("../../../assets/images/emotes/thonk.png"),
  },
  {
    name: "DogeHouse",
    short_names: ["DogeHouse"],
    keywords: ["dogehouse", "doge"],
    imageUrl: require("../../../assets/images/emotes/dogehouse.png"),
  },
  {
    name: "SadHouse",
    short_names: ["SadHouse"],
    keywords: ["dogehouse", "doge", "sadhouse"],
    imageUrl: require("../../../assets/images/emotes/sadhouse.png"),
  },
  {
    name: "CoolHouse",
    short_names: ["CoolHouse"],
    keywords: ["dogehouse", "doge", "coolhouse"],
    imageUrl: require("../../../assets/images/emotes/coolhouse.png"),
  },
  {
    name: "WinkHouse",
    short_names: ["WinkHouse"],
    keywords: ["dogehouse", "doge", "winkhouse"],
    imageUrl: require("../../../assets/images/emotes/winkhouse.png"),
  },
  {
    name: "SupriseHouse",
    short_names: ["SupriseHouse"],
    keywords: ["dogehouse", "doge", "suprisehouse", "shock"],
    imageUrl: require("../../../assets/images/emotes/suprisehouse.png"),
  },
  {
    name: "NeutralHouse",
    short_names: ["NeutralHouse"],
    keywords: ["dogehouse", "doge", "neutralhouse"],
    imageUrl: require("../../../assets/images/emotes/neutralhouse.png"),
  },
  {
    name: "WAYTOODANK",
    short_names: ["WAYTOODANK"],
    keywords: ["dank", "feelsdankman", "waytoodank"],
    imageUrl: require("../../../assets/images/emotes/waytoodank.gif"),
  },
  {
    name: "CryptoBTC",
    short_names: ["CryptoBTC"],
    keywords: ["crypto", "btc", "bitcoin"],
    imageUrl: require("../../../assets/images/emotes/cryptoBTC.png"),
  },
  {
    name: "CryptoETH",
    short_names: ["CryptoETH"],
    keywords: ["crypto", "eth", "ethereum"],
    imageUrl: require("../../../assets/images/emotes/cryptoETH.png"),
  },
  {
    name: "CryptoBNB",
    short_names: ["CryptoBNB"],
    keywords: ["crypto", "bnb", "binance"],
    imageUrl: require("../../../assets/images/emotes/cryptoBNB.png"),
  },
  {
    name: "CryptoLTC",
    short_names: ["CryptoLTC"],
    keywords: ["crypto", "ltc", "litecoin"],
    imageUrl: require("../../../assets/images/emotes/cryptoLTC.png"),
  },
  {
    name: "CryptoBCH",
    short_names: ["CryptoBCH"],
    keywords: ["crypto", "bch", "bitcoin", "bitcoincash"],
    imageUrl: require("../../../assets/images/emotes/cryptoBCH.png"),
  },
  {
    name: "CryptoDOGE",
    short_names: ["CryptoDOGE"],
    keywords: ["crypto", "doge", "dogecoin", "bestcoin"],
    imageUrl: require("../../../assets/images/emotes/cryptoDOGE.png"),
  },
  {
    name: "CryptoSUSHI",
    short_names: ["CryptoSUSHI"],
    keywords: ["crypto", "sushi", "swap", "sushiswap"],
    imageUrl: require("../../../assets/images/emotes/cryptoSUSHI.png"),
  },
  {
    name: "CryptoTRON",
    short_names: ["CryptoTRON"],
    keywords: ["crypto", "tron"],
    imageUrl: require("../../../assets/images/emotes/cryptoTron.png"),
  },
  {
    name: "CryptoZEC",
    short_names: ["CryptoZEC"],
    keywords: ["crypto", "zec", "zcash"],
    imageUrl: require("../../../assets/images/emotes/cryptoZEC.png"),
  },
  {
    name: "CryptoETC",
    short_names: ["CryptoETC"],
    keywords: ["crypto", "etc", "ethereum", "ethereumclassic"],
    imageUrl: require("../../../assets/images/emotes/cryptoETC.png"),
  },
  {
    name: "CryptoCAKE",
    short_names: ["CryptoCAKE"],
    keywords: ["crypto", "cake", "swap", "pancakeswap"],
    imageUrl: require("../../../assets/images/emotes/cryptoCAKE.png"),
  },
  {
    name: "CryptoADA",
    short_names: ["CryptoADA"],
    keywords: ["crypto", "ada", "cardano"],
    imageUrl: require("../../../assets/images/emotes/cryptoADA.png"),
  },
  {
    name: "CryptoXRP",
    short_names: ["CryptoXRP"],
    keywords: ["crypto", "xrp", "ripple"],
    imageUrl: require("../../../assets/images/emotes/cryptoXRP.png"),
  },
  {
    name: "CryptoUSDC",
    short_names: ["CryptoUSDC"],
    keywords: ["crypto", "usdc", "usdcoin"],
    imageUrl: require("../../../assets/images/emotes/cryptoUSDC.png"),
  },
  {
    name: "DodgyCoin",
    short_names: ["DodgyCoin"],
    keywords: ["crypto", "doge", "dodgycoin"],
    imageUrl: require("../../../assets/images/emotes/dodgyCoin.png"),
  },
  {
    name: "pepeBCKL",
    short_names: ["pepeBCKL"],
    keywords: [
      "pepebckl",
      "bckl",
      "pepe",
      "malarkey",
      "jesse",
      "penguin",
      "stallman",
      "freesoftware",
      "fsf",
      "charlie",
      "kernel",
      "lab",
      "kernellab",
      "computing",
      "jessecharlie",
      "linux",
      "torvalds",
    ],
    imageUrl: require("../../../assets/images/emotes/pepeBCKL.png"),
  },
  {
    name: "5Head",
    short_names: ["5Head"],
    keywords: ["5head", "big", "brain", "bigbrain", "smart"],
    imageUrl: require("../../../assets/images/emotes/5Head.png"),
  },
  {
    name: "AYAYA",
    short_names: ["AYAYA"],
    keywords: ["ayaya"],
    imageUrl: require("../../../assets/images/emotes/AYAYA.png"),
  },
  {
    name: "babaYEP",
    short_names: ["babaYEP"],
    keywords: ["babayep", "baba", "yep"],
    imageUrl: require("../../../assets/images/emotes/babaYEP.png"),
  },
  {
    name: "BBoomer",
    short_names: ["BBoomer"],
    keywords: ["bboomer", "boomer"],
    imageUrl: require("../../../assets/images/emotes/BBoomer.gif"),
  },
  {
    name: "BebeLa",
    short_names: ["BebeLa"],
    keywords: ["bebela", "bebe"],
    imageUrl: require("../../../assets/images/emotes/BebeLa.png"),
  },
  {
    name: "BERN",
    short_names: ["BERN"],
    keywords: [
      "bern",
      "notmeus",
      "bernie",
      "sanders",
      "berniesanders",
      "bernard",
      "socialism",
      "socialist",
      "comrade",
      "democrat",
      "malarkey",
      "biden",
      "joe",
      "joebiden",
      "us",
      "usa",
      "america",
    ],
    imageUrl: require("../../../assets/images/emotes/BERN.png"),
  },
  {
    name: "bidenJAM",
    short_names: ["bidenJAM"],
    keywords: [
      "bidenjam",
      "jam",
      "jamjam",
      "malarkey",
      "ridinwithbiden",
      "icecream",
      "joe",
      "biden",
      "joebiden",
      "46",
      "president",
      "laser",
      "potus",
      "democrat",
      "us",
      "usa",
      "america",
    ],
    imageUrl: require("../../../assets/images/emotes/bidenJAM.gif"),
  },
  {
    name: "Playa",
    short_names: ["Playa"],
    keywords: ["Playa"],
    imageUrl: require("../../../assets/images/emotes/Playa.png"),
  },
  {
    name: "IGetIt",
    short_names: ["IGetIt"],
    keywords: ["IGetIt", "Smile", "PepeLa", "Smug"],
    imageUrl: require("../../../assets/images/emotes/IGetIt.png"),
  },
  {
    name: "BLANKIES",
    short_names: ["BLANKIES"],
    keywords: ["blankies", "jammies", "blanket", "dance"],
    imageUrl: require("../../../assets/images/emotes/BLANKIES.gif"),
  },
  {
    name: "BOGGED",
    short_names: ["BOGGED"],
    keywords: [
      "bogged",
      "bog",
      "hello",
      "phone",
      "iphone",
      "calling",
      "call",
      "phonecall",
    ],
    imageUrl: require("../../../assets/images/emotes/BOGGED.png"),
  },
  {
    name: "Clap",
    short_names: ["Clap"],
    keywords: ["clap", "clapping"],
    imageUrl: require("../../../assets/images/emotes/Clap.gif"),
  },
  {
    name: "COGGERS",
    short_names: ["COGGERS"],
    keywords: ["coggers", "pog", "pogu", "poggies", "poggers", "pogger"],
    imageUrl: require("../../../assets/images/emotes/COGGERS.gif"),
  },
  {
    name: "COPIUM",
    short_names: ["COPIUM"],
    keywords: ["copium", "cope"],
    imageUrl: require("../../../assets/images/emotes/COPIUM.png"),
  },
  {
    name: "coronaS",
    short_names: ["coronaS"],
    keywords: ["coronas", "corona", "mask", "covid"],
    imageUrl: require("../../../assets/images/emotes/coronaS.png"),
  },
  {
    name: "CrabPls",
    short_names: ["CrabPls"],
    keywords: ["crabpls", "crab", "pls", "plz", "please"],
    imageUrl: require("../../../assets/images/emotes/crabpls.gif"),
  },
  {
    name: "DANKHACKERMANS",
    short_names: ["DANKHACKERMANS"],
    keywords: [
      "dankhackermans",
      "dank",
      "hacker",
      "hackermans",
      "keyboard",
      "typing",
      "computer",
      "coding",
      "coder",
      "code",
      "virus",
      "malware",
    ],
    imageUrl: require("../../../assets/images/emotes/DANKHACKERMANS.gif"),
  },
  {
    name: "dankHug",
    short_names: ["dankHug"],
    keywords: ["dankhug", "dank", "hug"],
    imageUrl: require("../../../assets/images/emotes/dankHug.png"),
  },
  {
    name: "DANKIES",
    short_names: ["DANKIES"],
    keywords: ["dankies", "dank"],
    imageUrl: require("../../../assets/images/emotes/DANKIES.gif"),
  },
  {
    name: "DewTime",
    short_names: ["DewTime"],
    keywords: ["dewtime", "mountaindew", "dew", "moutain", "time"],
    imageUrl: require("../../../assets/images/emotes/DewTime.gif"),
  },
  {
    name: "EZ",
    short_names: ["EZ"],
    keywords: ["ez"],
    imageUrl: require("../../../assets/images/emotes/EZ.png"),
  },
  {
    name: "F",
    short_names: ["F"],
    keywords: ["f"],
    imageUrl: require("../../../assets/images/emotes/F.gif"),
  },
  {
    name: "FeelsDankMan",
    short_names: ["FeelsDankMan"],
    keywords: ["feelsdankman", "feels", "feel", "dank", "man"],
    imageUrl: require("../../../assets/images/emotes/FeelsDankMan.png"),
  },
  {
    name: "FeelsOkayMan",
    short_names: ["FeelsOkayMan"],
    keywords: ["feelsokayman", "feels", "feel", "okay", "man"],
    imageUrl: require("../../../assets/images/emotes/FeelsOkayMan.png"),
  },
  {
    name: "FeelsStrongMan",
    short_names: ["FeelsStrongMan"],
    keywords: ["feelsstrongman", "feels", "feel", "strong", "man"],
    imageUrl: require("../../../assets/images/emotes/FeelsStrongMan.png"),
  },
  {
    name: "FeelsWeirdMan",
    short_names: ["FeelsWeirdMan"],
    keywords: ["feelsweirdman", "feels", "feel", "weird", "man"],
    imageUrl: require("../../../assets/images/emotes/FeelsWeirdMan.png"),
  },
  {
    name: "gachiHYPER",
    short_names: ["gachiHYPER"],
    keywords: ["gachihyper", "gachi", "hyper", "coomer"],
    imageUrl: require("../../../assets/images/emotes/gachiHYPER.gif"),
  },
  {
    name: "GRUG",
    short_names: ["GRUG"],
    keywords: ["grug"],
    imageUrl: require("../../../assets/images/emotes/GRUG.png"),
  },
  {
    name: "GuitarTime",
    short_names: ["GuitarTime"],
    keywords: ["guitartime", "guitar", "time"],
    imageUrl: require("../../../assets/images/emotes/GuitarTime.gif"),
  },
  {
    name: "HACKERMANS",
    short_names: ["HACKERMANS"],
    keywords: [
      "hackermans",
      "hacker",
      "keyboard",
      "typing",
      "computer",
      "coding",
      "coder",
      "code",
      "virus",
      "malware",
    ],
    imageUrl: require("../../../assets/images/emotes/HACKERMANS.gif"),
  },
  {
    name: "HandsUp",
    short_names: ["HandsUp"],
    keywords: ["handsup", "hands", "up", "hand"],
    imageUrl: require("../../../assets/images/emotes/HandsUp.png"),
  },
  {
    name: "hasanHyperSmash",
    short_names: ["hasanHyperSmash"],
    keywords: [
      "hasanhypersmash",
      "hasan",
      "hasanabi",
      "hasanpiker",
      "hyper",
      "smash",
    ],
    imageUrl: require("../../../assets/images/emotes/hasanHyperSmash.gif"),
  },
  {
    name: "hasanSmash",
    short_names: ["hasanSmash"],
    keywords: ["hasansmash", "hasan", "hasanabi", "hasanpiker", "smash"],
    imageUrl: require("../../../assets/images/emotes/hasanSmash.gif"),
  },
  {
    name: "HasanWalk",
    short_names: ["HasanWalk"],
    keywords: [
      "hasanwalk",
      "hasan",
      "hasanabi",
      "hasanpiker",
      "walk",
      "walking",
    ],
    imageUrl: require("../../../assets/images/emotes/HasanWalk.gif"),
  },
  {
    name: "hasHyperJAM",
    short_names: ["hasHyperJAM"],
    keywords: [
      "hashyperjam",
      "hasan",
      "hasanabi",
      "hasanpiker",
      "hyper",
      "jam",
      "jamjam",
      "jammies",
    ],
    imageUrl: require("../../../assets/images/emotes/hasHyperJAM.gif"),
  },
  {
    name: "hasPls",
    short_names: ["hasPls"],
    keywords: [
      "haspls",
      "please",
      "pls",
      "plz",
      "hasan",
      "hasanabi",
      "hasanpiker",
    ],
    imageUrl: require("../../../assets/images/emotes/hasPls.gif"),
  },
  {
    name: "hasRock",
    short_names: ["hasRock"],
    keywords: [
      "hasrock",
      "spongebob",
      "patrick",
      "hasan",
      "hasanabi",
      "hasanpiker",
      "rock",
    ],
    imageUrl: require("../../../assets/images/emotes/hasRock.gif"),
  },
  {
    name: "hasTasty",
    short_names: ["hasTasty"],
    keywords: [
      "hastasty",
      "hasan",
      "tasty",
      "yum",
      "yummy",
      "hasanabi",
      "hasanpiker",
    ],
    imageUrl: require("../../../assets/images/emotes/hasTasty.gif"),
  },
  {
    name: "HYPERCLAP",
    short_names: ["HYPERCLAP"],
    keywords: ["hyperclap", "hyper", "clap"],
    imageUrl: require("../../../assets/images/emotes/HYPERCLAP.gif"),
  },
  {
    name: "hyperHammer",
    short_names: ["hyperHammer"],
    keywords: ["hyperhammer", "hyper", "hammer"],
    imageUrl: require("../../../assets/images/emotes/hyperHammer.gif"),
  },
  {
    name: "HYPERITALIANHANDS",
    short_names: ["HYPERITALIANHANDS"],
    keywords: [
      "hyperitalianhands",
      "hyper",
      "italian",
      "hands",
      "hand",
      "italy",
      "ovahere",
    ],
    imageUrl: require("../../../assets/images/emotes/HYPERITALIANHANDS.gif"),
  },
  {
    name: "HYPERPOGGER",
    short_names: ["HYPERPOGGER"],
    keywords: ["hyperpogger", "hyper", "pog", "pogger", "poggies"],
    imageUrl: require("../../../assets/images/emotes/HYPERPOGGER.gif"),
  },
  {
    name: "HYPERPOGO",
    short_names: ["HYPERPOGO"],
    keywords: [
      "hyperpogo",
      "hyper",
      "pog",
      "pogo",
      "azan",
      "poggies",
      "poggers",
      "pogger",
    ],
    imageUrl: require("../../../assets/images/emotes/HYPERPOGO.gif"),
  },
  {
    name: "ItalianHands",
    short_names: ["ItalianHands"],
    keywords: ["italianhands", "ovahere", "italian", "hands", "hand", "italy"],
    imageUrl: require("../../../assets/images/emotes/ItalianHands.gif"),
  },
  {
    name: "Jammies",
    short_names: ["Jammies"],
    keywords: ["jammies", "jam", "jamjam", "dance", "vibe"],
    imageUrl: require("../../../assets/images/emotes/Jammies.gif"),
  },
  {
    name: "KEKebab",
    short_names: ["KEKebab"],
    keywords: [
      "kekebab",
      "kek",
      "kebab",
      "omegalul",
      "lol",
      "lmao",
      "haha",
      "ha",
      "ja",
      "jaja",
      "kekw",
    ],
    imageUrl: require("../../../assets/images/emotes/KEKebab.png"),
  },
  {
    name: "KEKW",
    short_names: ["KEKW"],
    keywords: [
      "kekw",
      "kek",
      "omegalul",
      "lol",
      "lmao",
      "haha",
      "ha",
      "ja",
      "jaja",
    ],
    imageUrl: require("../../../assets/images/emotes/KEKW.png"),
  },
  {
    name: "KEKWait",
    short_names: ["KEKWait"],
    keywords: [
      "kekwait",
      "lul",
      "omegalul",
      "lol",
      "lmao",
      "wait",
      "kek",
      "ha",
    ],
    imageUrl: require("../../../assets/images/emotes/KEKWait.png"),
  },
  {
    name: "KKapitalist",
    short_names: ["KKapitalist"],
    keywords: ["kkapitalist", "kapitalist", "capitalist", "business"],
    imageUrl: require("../../../assets/images/emotes/KKapitalist.png"),
  },
  {
    name: "KKomrade",
    short_names: ["KKomrade"],
    keywords: ["kkomrade", "komrade", "comrade"],
    imageUrl: require("../../../assets/images/emotes/KKomrade.png"),
  },
  {
    name: "KKonaW",
    short_names: ["KKonaW"],
    keywords: ["kkonaw"],
    imageUrl: require("../../../assets/images/emotes/KKonaW.png"),
  },
  {
    name: "KKop",
    short_names: ["KKop"],
    keywords: [
      "kkop",
      "kop",
      "kops",
      "cop",
      "cops",
      "police",
      "acab",
      "blueline",
    ],
    imageUrl: require("../../../assets/images/emotes/KKop.png"),
  },
  {
    name: "LULW",
    short_names: ["LULW"],
    keywords: ["lulw", "lul", "lol", "lmao", "omegalul"],
    imageUrl: require("../../../assets/images/emotes/LULW.png"),
  },
  {
    name: "lulWut",
    short_names: ["lulWut"],
    keywords: [
      "lulwut",
      "lul",
      "lmao",
      "lol",
      "wut",
      "what",
      "wat",
      "wtf",
      "omegalul",
      "ha",
      "haha",
      "ja",
      "jaja",
    ],
    imageUrl: require("../../../assets/images/emotes/lulWut.png"),
  },
  {
    name: "MALARKEY",
    short_names: ["MALARKEY"],
    keywords: [
      "malarkey",
      "ridinwithbiden",
      "icecream",
      "joe",
      "biden",
      "joebiden",
      "46",
      "president",
      "laser",
      "potus",
      "democrat",
      "us",
      "usa",
      "america",
    ],
    imageUrl: require("../../../assets/images/emotes/MALARKEY.gif"),
  },
  {
    name: "MmmHmm",
    short_names: ["MmmHmm"],
    keywords: [
      "mmmhmm",
      "mmm",
      "mmmm",
      "hmm",
      "hmmm",
      "mmmmhmmm",
      "mmmmhmm",
      "mmmhmmm",
    ],
    imageUrl: require("../../../assets/images/emotes/MmmHmm.gif"),
  },
  {
    name: "modCheck",
    short_names: ["modCheck"],
    keywords: [
      "modcheck",
      "mods",
      "mod",
      "check",
      "spongebob",
      "ask",
      "askers",
      "whoasked",
      "where",
      "look",
      "fish",
      "oooo",
    ],
    imageUrl: require("../../../assets/images/emotes/modCheck.gif"),
  },
  {
    name: "ModTime",
    short_names: ["ModTime"],
    keywords: ["modtime", "mod", "mods", "time"],
    imageUrl: require("../../../assets/images/emotes/ModTime.gif"),
  },
  {
    name: "monkaHmm",
    short_names: ["monkaHmm"],
    keywords: ["monkahmm", "monka", "hmmm", "hmm"],
    imageUrl: require("../../../assets/images/emotes/monkaHmm.png"),
  },
  {
    name: "monkaStare",
    short_names: ["monkaStare"],
    keywords: ["monkastare", "stare", "monka"],
    imageUrl: require("../../../assets/images/emotes/monkaStare.png"),
  },
  {
    name: "monkaSTEER",
    short_names: ["monkaSTEER"],
    keywords: ["monkasteer", "monka", "steer", "ridinwithbiden"],
    imageUrl: require("../../../assets/images/emotes/monkaSTEER.gif"),
  },
  {
    name: "monkaW",
    short_names: ["monkaW"],
    keywords: ["monkaw", "monka"],
    imageUrl: require("../../../assets/images/emotes/monkaW.png"),
  },
  {
    name: "neffHyperJAM",
    short_names: ["neffHyperJAM"],
    keywords: [
      "neffhyperjam",
      "hyperjam",
      "jam",
      "jammies",
      "boppin",
      "dj",
      "jamjam",
      "neff",
      "will",
      "willneff",
    ],
    imageUrl: require("../../../assets/images/emotes/neffHyperJAM.gif"),
  },
  {
    name: "NODDERS",
    short_names: ["NODDERS"],
    keywords: ["nodders", "nod", "noddies"],
    imageUrl: require("../../../assets/images/emotes/NODDERS.gif"),
  },
  {
    name: "NOPERS",
    short_names: ["NOPERS"],
    keywords: ["nopers", "no", "nope"],
    imageUrl: require("../../../assets/images/emotes/NOPERS.gif"),
  },
  {
    name: "nymnCorn",
    short_names: ["nymnCorn"],
    keywords: ["nymncorn", "mmm", "corn", "nymn"],
    imageUrl: require("../../../assets/images/emotes/nymnCorn.gif"),
  },
  {
    name: "OkayChamp",
    short_names: ["OkayChamp"],
    keywords: ["okaychamp", "okay", "champ"],
    imageUrl: require("../../../assets/images/emotes/OkayChamp.png"),
  },
  {
    name: "OMEGALUL",
    short_names: ["OMEGALUL"],
    keywords: ["omegalul", "lol", "lmao", "lul", "ha", "haha", "ja", "jaja"],
    imageUrl: require("../../../assets/images/emotes/omegalul.png"),
  },
  {
    name: "OOOO",
    short_names: ["OOOO"],
    keywords: ["oooo", "fish"],
    imageUrl: require("../../../assets/images/emotes/OOOO.gif"),
  },
  {
    name: "PagChomp",
    short_names: ["PagChomp"],
    keywords: ["pagchomp", "pag", "chomp"],
    imageUrl: require("../../../assets/images/emotes/PagChomp.png"),
  },
  {
    name: "PainsChamp",
    short_names: ["PainsChamp"],
    keywords: ["painschamp", "pains", "champ", "pain"],
    imageUrl: require("../../../assets/images/emotes/PainsChamp.png"),
  },
  {
    name: "PauseChamp",
    short_names: ["PauseChamp"],
    keywords: ["pausechamp", "pause", "champ"],
    imageUrl: require("../../../assets/images/emotes/PauseChamp.png"),
  },
  {
    name: "peepoArrive",
    short_names: ["peepoArrive"],
    keywords: [
      "peepoarrive",
      "peepo",
      "pepo",
      "arrive",
      "here",
      "welcome",
      "hey",
      "wave",
      "hi",
      "hello",
      "howdy",
    ],
    imageUrl: require("../../../assets/images/emotes/peepoArrive.gif"),
  },
  {
    name: "peepoBaba",
    short_names: ["peepoBaba"],
    keywords: ["peepobaba", "peepo", "pepo", "baba"],
    imageUrl: require("../../../assets/images/emotes/peepoBaba.png"),
  },
  {
    name: "peepoBye",
    short_names: ["peepoBye"],
    keywords: ["peepobye", "peepo", "pepo", "bye"],
    imageUrl: require("../../../assets/images/emotes/peepoBye.gif"),
  },
  {
    name: "peepoChat",
    short_names: ["peepoChat"],
    keywords: ["peepochat", "peepo", "pepo", "chat"],
    imageUrl: require("../../../assets/images/emotes/peepoChat.gif"),
  },
  {
    name: "peepoCheer",
    short_names: ["peepoCheer"],
    keywords: ["peepocheer", "peepo", "pepo", "cheer"],
    imageUrl: require("../../../assets/images/emotes/peepoCheer.gif"),
  },
  {
    name: "peepoClap",
    short_names: ["peepoClap"],
    keywords: ["peepoclap", "peepo", "pepo", "clap"],
    imageUrl: require("../../../assets/images/emotes/peepoClap.gif"),
  },
  {
    name: "peepoD",
    short_names: ["peepoD"],
    keywords: ["peepod", "peepo", "pepo"],
    imageUrl: require("../../../assets/images/emotes/peepoD.gif"),
  },
  {
    name: "peepoFat",
    short_names: ["peepoFat"],
    keywords: ["peepofat", "peepo", "pepo", "fat", "houngry", "hungry", "food"],
    imageUrl: require("../../../assets/images/emotes/peepoFat.png"),
  },
  {
    name: "peepoGiggles",
    short_names: ["peepoGiggles"],
    keywords: ["peepogiggles", "pepo", "peepo", "giggle", "giggles"],
    imageUrl: require("../../../assets/images/emotes/peepoGiggles.gif"),
  },
  {
    name: "peepoHey",
    short_names: ["peepoHey"],
    keywords: [
      "peepohey",
      "peepo",
      "wave",
      "pepo",
      "hey",
      "hi",
      "hello",
      "howdy",
      "welcome",
    ],
    imageUrl: require("../../../assets/images/emotes/peepoHey.gif"),
  },
  {
    name: "peepoJAMMER",
    short_names: ["peepoJAMMER"],
    keywords: ["peepojammer", "peepo", "pepo", "jam", "jammer", "jamjam"],
    imageUrl: require("../../../assets/images/emotes/peepoJAMMER.gif"),
  },
  {
    name: "peepoKiss",
    short_names: ["peepoKiss"],
    keywords: ["peepokiss", "peepo", "pepo", "kiss", "love"],
    imageUrl: require("../../../assets/images/emotes/peepoKiss.png"),
  },
  {
    name: "peepoLeave",
    short_names: ["peepoLeave"],
    keywords: ["peepoleave", "peepo", "pepo", "leave", "exit", "bye"],
    imageUrl: require("../../../assets/images/emotes/peepoLeave.gif"),
  },
  {
    name: "peepoPog",
    short_names: ["peepoPog"],
    keywords: ["peepopog", "peepo", "pepo", "pog"],
    imageUrl: require("../../../assets/images/emotes/peepoPog.png"),
  },
  {
    name: "peepoPogO",
    short_names: ["peepoPogO"],
    keywords: ["peepopogo", "peepo", "pepo", "pog", "pogo"],
    imageUrl: require("../../../assets/images/emotes/peepoPogO.png"),
  },
  {
    name: "peepoRun",
    short_names: ["peepoRun"],
    keywords: ["peeporun", "peepo", "pepo", "run"],
    imageUrl: require("../../../assets/images/emotes/peepoRun.gif"),
  },
  {
    name: "peepoShy",
    short_names: ["peepoShy"],
    keywords: ["peeposhy", "peepo", "pepo", "shy"],
    imageUrl: require("../../../assets/images/emotes/peepoShy.gif"),
  },
  {
    name: "peepoSnow",
    short_names: ["peepoSnow"],
    keywords: [
      "peeposnow",
      "peepo",
      "pepo",
      "snow",
      "christmas",
      "cold",
      "holidays",
    ],
    imageUrl: require("../../../assets/images/emotes/peepoSnow.gif"),
  },
  {
    name: "peepoT",
    short_names: ["peepoT"],
    keywords: ["peepot", "peepo", "pepo"],
    imageUrl: require("../../../assets/images/emotes/peepoT.gif"),
  },
  {
    name: "peepoWeird",
    short_names: ["peepoWeird"],
    keywords: ["peepoweird", "peepo", "pepo", "weird"],
    imageUrl: require("../../../assets/images/emotes/peepoWeird.png"),
  },
  {
    name: "pepeCD",
    short_names: ["pepeCD"],
    keywords: ["pepecd", "pepe", "cd"],
    imageUrl: require("../../../assets/images/emotes/pepeCD.gif"),
  },
  {
    name: "PepegeHmm",
    short_names: ["PepegeHmm"],
    keywords: ["pepegehmm", "pepege", "pepe", "hmm", "hmmm"],
    imageUrl: require("../../../assets/images/emotes/PepegeHmm.png"),
  },
  {
    name: "PepeHands",
    short_names: ["PepeHands"],
    keywords: ["pepehands", "pepe", "hands"],
    imageUrl: require("../../../assets/images/emotes/PepeHands.png"),
  },
  {
    name: "pepeJAMJAM",
    short_names: ["pepeJAMJAM"],
    keywords: ["pepejamjam", "pepe", "jam"],
    imageUrl: require("../../../assets/images/emotes/pepeJAMJAM.gif"),
  },
  {
    name: "pepeJAM",
    short_names: ["pepeJAM"],
    keywords: ["pepeJAM", "pepe"],
    imageUrl: require("../../../assets/images/emotes/pepejam.gif"),
  },
  {
    name: "PepeLa",
    short_names: ["PepeLa"],
    keywords: ["pepela", "pepe"],
    imageUrl: require("../../../assets/images/emotes/PepeLa.png"),
  },
  {
    name: "PepeLaugh",
    short_names: ["PepeLaugh"],
    keywords: ["pepelaugh", "pepe", "laugh"],
    imageUrl: require("../../../assets/images/emotes/PepeLaugh.gif"),
  },
  {
    name: "pepeMeltdown",
    short_names: ["pepeMeltdown"],
    keywords: ["pepemeltdown", "pepe", "meltdown"],
    imageUrl: require("../../../assets/images/emotes/pepeMeltdown.gif"),
  },
  {
    name: "pepeP",
    short_names: ["pepeP"],
    keywords: ["pepep", "pepe"],
    imageUrl: require("../../../assets/images/emotes/pepeP.gif"),
  },
  {
    name: "PepeS",
    short_names: ["PepeS"],
    keywords: ["pepes", "pepe"],
    imageUrl: require("../../../assets/images/emotes/PepeS.gif"),
  },
  {
    name: "PepeSpit",
    short_names: ["PepeSpit"],
    keywords: ["pepespit", "pepe", "spit"],
    imageUrl: require("../../../assets/images/emotes/PepeSpit.gif"),
  },
  {
    name: "pepeW",
    short_names: ["pepeW"],
    keywords: ["pepew", "pepe"],
    imageUrl: require("../../../assets/images/emotes/pepeW.gif"),
  },
  {
    name: "PepoG",
    short_names: ["PepoG"],
    keywords: ["pepog", "pepo", "peepo"],
    imageUrl: require("../../../assets/images/emotes/PepoG.png"),
  },
  {
    name: "Pog",
    short_names: ["Pog"],
    keywords: ["pog", "poggies", "pogger", "poggers"],
    imageUrl: require("../../../assets/images/emotes/Pog.png"),
  },
  {
    name: "POGGERS",
    short_names: ["POGGERS"],
    keywords: ["poggers", "pog", "poggies", "pogger"],
    imageUrl: require("../../../assets/images/emotes/POGGERS.png"),
  },
  {
    name: "POGGIES",
    short_names: ["POGGIES"],
    keywords: ["poggies", "pog", "pogger"],
    imageUrl: require("../../../assets/images/emotes/POGGIES.png"),
  },
  {
    name: "PogO",
    short_names: ["PogO"],
    keywords: ["pogo", "pog", "azan"],
    imageUrl: require("../../../assets/images/emotes/PogO.png"),
  },
  {
    name: "PogU",
    short_names: ["PogU"],
    keywords: ["pogu", "pog"],
    imageUrl: require("../../../assets/images/emotes/PogU.png"),
  },
  {
    name: "ppHop",
    short_names: ["ppHop"],
    keywords: ["pphop", "hop"],
    imageUrl: require("../../../assets/images/emotes/ppHop.gif"),
  },
  {
    name: "ppOverheat",
    short_names: ["ppOverheat"],
    keywords: ["ppoverheat", "overheat"],
    imageUrl: require("../../../assets/images/emotes/ppOverheat.gif"),
  },
  {
    name: "ppPoof",
    short_names: ["ppPoof"],
    keywords: ["pppoof", "poof"],
    imageUrl: require("../../../assets/images/emotes/ppPoof.gif"),
  },
  {
    name: "Prayge",
    short_names: ["Prayge"],
    keywords: ["prayge", "pray", "god"],
    imageUrl: require("../../../assets/images/emotes/Prayge.png"),
  },
  {
    name: "ratJAM",
    short_names: ["ratJAM"],
    keywords: ["ratjam", "rat", "jam"],
    imageUrl: require("../../../assets/images/emotes/ratJAM.gif"),
  },
  {
    name: "REE",
    short_names: ["REE"],
    keywords: ["ree", "reeee"],
    imageUrl: require("../../../assets/images/emotes/REE.png"),
  },
  {
    name: "SillyChamp",
    short_names: ["SillyChamp"],
    keywords: ["sillychamp", "silly", "champ"],
    imageUrl: require("../../../assets/images/emotes/SillyChamp.png"),
  },
  {
    name: "SmokeTime",
    short_names: ["SmokeTime"],
    keywords: ["smoketime", "smoke"],
    imageUrl: require("../../../assets/images/emotes/SmokeTime.gif"),
  },
  {
    name: "SWOONER",
    short_names: ["SWOONER"],
    keywords: ["swooner"],
    imageUrl: require("../../../assets/images/emotes/SWOONER.png"),
  },
  {
    name: "TeaTime",
    short_names: ["TeaTime"],
    keywords: ["teatime", "tea"],
    imageUrl: require("../../../assets/images/emotes/TeaTime.gif"),
  },
  {
    name: "TomatoTime",
    short_names: ["TomatoTime"],
    keywords: ["tomatotime", "tomato"],
    imageUrl: require("../../../assets/images/emotes/TomatoTime.gif"),
  },
  {
    name: "unPOGGERS",
    short_names: ["unPOGGERS"],
    keywords: ["unpoggers", "poggers", "pog", "unpoggies"],
    imageUrl: require("../../../assets/images/emotes/unPOGGERS.png"),
  },
  {
    name: "WeirdChamp",
    short_names: ["WeirdChamp"],
    keywords: ["weirdchamp", "weird", "champ"],
    imageUrl: require("../../../assets/images/emotes/WeirdChamp.png"),
  },
  {
    name: "Weirdge",
    short_names: ["Weirdge"],
    keywords: ["weirdge", "weird"],
    imageUrl: require("../../../assets/images/emotes/Weirdge.png"),
  },
  {
    name: "WhatChamp",
    short_names: ["WhatChamp"],
    keywords: ["whatchamp", "what", "champ"],
    imageUrl: require("../../../assets/images/emotes/WhatChamp.png"),
  },
  {
    name: "WICKED",
    short_names: ["WICKED"],
    keywords: ["wicked"],
    imageUrl: require("../../../assets/images/emotes/WICKED.png"),
  },
  {
    name: "widepeepoHappy",
    short_names: ["widepeepoHappy"],
    keywords: ["widepeepohappy", "peepohappy", "peepo", "happy"],
    imageUrl: require("../../../assets/images/emotes/widepeepoHappy.png"),
  },
  {
    name: "widepeepoSad",
    short_names: ["widepeepoSad"],
    keywords: ["widepeeposad", "peeposad", "peepo", "sad"],
    imageUrl: require("../../../assets/images/emotes/widepeepoSad.png"),
  },
  {
    name: "WineTime",
    short_names: ["WineTime"],
    keywords: ["winetime", "wine"],
    imageUrl: require("../../../assets/images/emotes/WineTime.gif"),
  },
  {
    name: "YEP",
    short_names: ["YEP"],
    keywords: ["yep"],
    imageUrl: require("../../../assets/images/emotes/YEP.png"),
  },
  {
    name: "ZZoomer",
    short_names: ["ZZoomer"],
    keywords: ["zzoomer", "zoomer"],
    imageUrl: require("../../../assets/images/emotes/ZZoomer.gif"),
  },
  {
    name: "Doge3D",
    short_names: ["Doge3D"],
    keywords: ["doge3d", "doge", "3d"],
    imageUrl: require("../../../assets/images/emotes/doge3d.gif"),
  },
  {
    name: "DogeCool",
    short_names: ["DogeCool"],
    keywords: ["dogecool", "doge", "cool"],
    imageUrl: require("../../../assets/images/emotes/dogecool.gif"),
  },
  {
    name: "ThugPepe",
    short_names: ["ThugPepe"],
    keywords: ["dogehouse", "doge", "thugpepe"],
    imageUrl: require("../../../assets/images/emotes/thugpepe.png"),
  },
  {
    name: "blaze",
    short_names: ["blaze"],
    keywords: ["blaze", "yes", "snark"],
    imageUrl: require("../../../assets/images/emotes/blaze.png"),
  },
  {
    name: "blobDance",
    short_names: ["blobDance"],
    keywords: ["blobDance", "vibe"],
    imageUrl: require("../../../assets/images/emotes/blobdance.gif"),
  },
  {
    name: "PepePls",
    short_names: ["PepePls"],
    keywords: ["PepePls", "pepe"],
    imageUrl: require("../../../assets/images/emotes/pepepls.gif"),
  },
  {
    name: "FeelsGoodMan",
    short_names: ["FeelsGoodMan"],
    keywords: ["FeelsGoodMan", "pepe"],
    imageUrl: require("../../../assets/images/emotes/feelsgoodman.png"),
  },
  {
    name: "GitHub",
    short_names: ["GitHub"],
    keywords: ["app", "git", "github"],
    imageUrl: require("../../../assets/images/emotes/github.png"),
  },
  {
    name: "Elixir",
    short_names: ["Elixir"],
    keywords: ["app", "elixir"],
    imageUrl: require("../../../assets/images/emotes/elixir.png"),
  },
  {
    name: "NextJS",
    short_names: ["NextJS"],
    keywords: ["app", "next", "js"],
    imageUrl: require("../../../assets/images/emotes/nextjs.png"),
  },
  {
    name: "React",
    short_names: ["React"],
    keywords: ["app", "react", "js"],
    imageUrl: require("../../../assets/images/emotes/react.png"),
  },
  {
    name: "Electron",
    short_names: ["Electron"],
    keywords: ["app", "electron"],
    imageUrl: require("../../../assets/images/emotes/electron.png"),
  },
  {
    name: "BeardGuyR",
    short_names: ["BeardGuyR"],
    keywords: ["meme", "beard", "guy"],
    imageUrl: require("../../../assets/images/emotes/beardguyright.png"),
  },
  {
    name: "BeardGuyL",
    short_names: ["BeardGuyL"],
    keywords: ["meme", "beard", "guy"],
    imageUrl: require("../../../assets/images/emotes/beardguyleft.png"),
  },
  {
    name: "MemeMan",
    short_names: ["MemeMan"],
    keywords: ["meme", "guy"],
    imageUrl: require("../../../assets/images/emotes/mememan.png"),
  },
  {
    name: "NPC",
    short_names: ["NPC"],
    keywords: ["meme", "npc", "guy"],
    imageUrl: require("../../../assets/images/emotes/npc.png"),
  },
  {
    name: "SmudgeCat",
    short_names: ["SMudgeCat"],
    keywords: ["meme", "cat"],
    imageUrl: require("../../../assets/images/emotes/smudgecat.png"),
  },
  {
    name: "Stonks",
    short_names: ["Stonks"],
    keywords: ["meme", "crypto", "guy"],
    imageUrl: require("../../../assets/images/emotes/stonks.png"),
  },
  {
    name: "Stinks",
    short_names: ["Stinks"],
    keywords: ["meme", "crypto", "guy"],
    imageUrl: require("../../../assets/images/emotes/stinks.png"),
  },
  {
    name: "IWMD",
    short_names: ["IWMD"],
    keywords: ["meme", "dude", "wednesday", "frog"],
    imageUrl: require("../../../assets/images/emotes/wednesday.png"),
  },
  {
    name: "PreSponge",
    short_names: ["PreSponge"],
    keywords: ["meme", "spongebob"],
    imageUrl: require("../../../assets/images/emotes/presponge.png"),
  },
  {
    name: "sPonGeBoB",
    short_names: ["sPonGeBoB"],
    keywords: ["meme", "spongebob"],
    imageUrl: require("../../../assets/images/emotes/sPonGeBoB.png"),
  },
  {
    name: "peepohappy",
    short_names: ["peepohappy"],
    keywords: ["peepohappy", "peepo", "pepe"],
    imageUrl: require("../../../assets/images/emotes/peepohappy.png"),
  },
  {
    name: "peepohug",
    short_names: ["peepohug"],
    keywords: ["peepohug", "peepo", "pepe"],
    imageUrl: require("../../../assets/images/emotes/peepohug.png"),
  },
  {
    name: "PurpleDogeHouse",
    short_names: ["PurpleDogeHouse"],
    keywords: ["purple", "dogehouse", "doge"],
    imageUrl: require("../../../assets/images/emotes/purpledogehouse.png"),
  },
  {
    name: "widepeepoPussy",
    short_names: ["widepeepoPussy"],
    keywords: ["widepeepoPussy", "peepo", "wide"],
    imageUrl: require("../../../assets/images/emotes/widepeepoPussy.png"),
  },
  {
    name: "RareParrot",
    short_names: ["RareParrot"],
    keywords: ["Rare", "Parrot", "party"],
    imageUrl: require("../../../assets/images/emotes/rareParrot.gif"),
  },
  {
    name: "OrangeDogeHouse",
    short_names: ["OrangeDogeHouse"],
    keywords: ["orange", "dogehouse", "doge"],
    imageUrl: require("../../../assets/images/emotes/orangedogehouse.png"),
  },
  {
    name: "CyanDogeHouse",
    short_names: ["CyanDogeHouse"],
    keywords: ["cyan", "dogehouse", "doge"],
    imageUrl: require("../../../assets/images/emotes/cyandogehouse.png"),
  },
  {
    name: "AngryKermit",
    short_names: ["AngryKermit"],
    keywords: ["kermit", "angry", "ak47"],
    imageUrl: require("../../../assets/images/emotes/angrykermit.png"),
  },
  {
    name: "DarthKermit",
    short_names: ["DarthKermit"],
    keywords: ["kermit", "star", "wars", "darth"],
    imageUrl: require("../../../assets/images/emotes/darthkermit.png"),
  },
  {
    name: "Anime Girl Pepe",
    short_names: ["AnimePepe"],
    keywords: ["pepe", "anime", "girl"],
    imageUrl: require("../../../assets/images/emotes/pepeanimegirl.png"),
  },
  {
    name: "TakeMyMoney",
    short_names: ["TakeMyMoney"],
    keywords: ["take", "my", "money", "shut", "up"],
    imageUrl: require("../../../assets/images/emotes/takemymoney.png"),
  },
  {
    name: "awyeah",
    short_names: ["awyeah"],
    keywords: ["aw", "yeah", "awyeah", "dancing"],
    imageUrl: require("../../../assets/images/emotes/awyeah.gif"),
  },
  {
    name: "ZeroTwoLul",
    short_names: ["ZTlul"],
    keywords: ["lul", "lol", "anime", "girl", "zerotwo"],
    imageUrl: require("../../../assets/images/emotes/zerotwolul.png"),
  },
  {
    name: "ZeroTwoSmug",
    short_names: ["ZTsmug"],
    keywords: ["smug", "anime", "girl", "zerotwo"],
    imageUrl: require("../../../assets/images/emotes/zerotwosmug.png"),
  },
  {
    name: "ZeroTwoThinking",
    short_names: ["ZTthinking"],
    keywords: ["thinking", "think", "anime", "girl", "zerotwo"],
    imageUrl: require("../../../assets/images/emotes/zerotwothinking.png"),
  },
  {
    name: "PartyParrot",
    short_names: ["PartyParrot"],
    keywords: ["party", "high", "parrot", "fun"],
    imageUrl: require("../../../assets/images/emotes/PartyParrot.gif"),
  },
  {
    name: "DogePls",
    short_names: ["DogePls"],
    keywords: ["doge", "please", "fun", "dance"],
    imageUrl: require("../../../assets/images/emotes/DogePls.gif"),
  },
  {
    name: "catDance",
    short_names: ["catDance"],
    keywords: ["cat", "dance", "party", "fun"],
    imageUrl: require("../../../assets/images/emotes/catDance.gif"),
  },
]; //.map((e) => ({ ...e, customCategory: "Custom", text: "", emoticons: [] }));

export const emoteMap: Record<string, ImageSourcePropType> = {};

customEmojis.forEach((e) => {
  emoteMap[e.name] = e.imageUrl;
});
