module.exports = {
  darkMode: "media",
  purge: ["./src/**/*.tsx", "./public/index.html"],
  theme: {
    fontFamily: {
      sans: [
        "Inter",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica",
        "Arial",
        "sans-serif",
      ],
      // mono: ["Menlo", "Monaco", "Courier New", "monospace"],
    },
    colors: {
      button: "var(--color-button-text)",
      gray: {
        100: "#DEE3EA",
        200: "#B2BDCD",
        300: "#5D7290",
        // 400: "#4F617A",
        // 500: "#404F64",
        // 600: "#323D4D",
        700: "#242C37",
        800: "#151A21",
        900: "#0B0E11",
      },
      primary: {
        100: "var(--color-primary-100)",
        200: "var(--color-primary-200)",
        300: "var(--color-primary-300)",
        600: "var(--color-primary-600)",
        700: "var(--color-primary-700)",
        800: "var(--color-primary-800)",
        900: "var(--color-primary-900)",
      },
      accent: {
        DEFAULT: "var(--color-accent)",
        hover: "var(--color-accent-hover)",
        disabled: "var(--color-accent-disabled)",
      },
    },
    spacing: {
      1: "5px",
      2: "10px",
      3: "15px",
      4: "20px",
      5: "30px",
      6: "40px",
      7: "60px",
    },
  },
  variants: {
    backgroundColor: ({ after }) => after(["disabled"]),
    textColor: ({ after }) => after(["disabled"]),
  },
  plugins: [],
};
