export { default as SmSolidCalendar } from './SmSolidCalendar'
export { default as SmSolidCompass } from './SmSolidCompass'
export { default as SmSolidFriends } from './SmSolidFriends'
export { default as SmSolidHome } from './SmSolidHome'
export { default as SmSolidNew } from './SmSolidNew'