name: kousa:tests
on:
  push:
    branches:
      - staging
    paths:
      - 'kousa/lib/**'
  pull_request:
    branches:
      - staging
    paths:
      - 'kousa/lib/**'
jobs:
  test:
    name: test-elixir
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kousa
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-elixir@v1
      with:
        otp-version: '22.2'
        elixir-version: '1.11'
    - name: fetch deps
      run: mix deps.get
      env:
          MIX_ENV: test
    - run: mix test
      id: test